### ISSUE TITLE
USSD CODES

### ISSUE THREAD

**Issue by salchee** [Seeed-Studio/Seeeduino_GPRS#10]
Is there anyway to check credit balance ? like codes *123#

**Comment by lanselambor** [comment]
@salchee Is *123# sent by SMS or Call? Can you describe more clearly?

**Comment by salchee** [comment]
its by call

**Comment by lanselambor** [comment]
@salchee Not sure if credit balance can be called by dialling a special code, because it's up to the mobile operators.

As I know in China all the mobile operators provide credit balance checking by replying a SMS if you send a special code to them .

**Comment by lanselambor** [comment]
@salchee AT cmd to operate USSD CODES like below,
AT+CUSD=1   // open USSD 
AT+CUSD=1,"*111#"

This page may help.
http://www.raviyp.com/embedded/190-sim900-sim800-ussd-code-at-commands-working-example

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.

**Comment by logicmagic2017** [comment]
what if by SMS, how to code USSD to check balance?

**Comment by lanselambor** [comment]
@logicmagic2017 Sorry USSD is not supported sending by SMS.
