### ISSUE TITLE
Seeeduino_GPRS

### ISSUE THREAD

**Issue by suhaakkus** [Seeed-Studio/Seeeduino_GPRS#13]
hi,
i am trying to use your gprs send sms codes with sim800l and want to learn the power key pin and power status pin of sim800l. there is only vcc rst rx tx gnd pins on the sim800l module. which of them are power reset pin and power key pin.
thank you!!!

**Comment by lakshanthad** [comment]
Hello,

Our product is based on SIM800H and the codes are supported for that. Do you mean you want to use a different module that is based on SIM800L?
